[build]
  command = "npm run build"
  publish = "dist"

# Redirect and proxy API calls to your external backend
# Replace YOUR-BACKEND-HOST with your actual backend host (e.g. my-app.onrender.com)
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-HOST/api/:splat"
  status = 200
  force = true
